---
name: Deploy

on: [push]

jobs:
  deploy:
    name: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Run Go Build
      run: make build
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: install serverless
      run: npm install -g serverless
    - name: serverless deploy
      run: serverless deploy --verbose
      env:
        TELEGRAM_TOKEN: ${{ secrets.DEPLOY_TELEGRAM_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
